org: fe23devs
service: mmdb

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::024848481193:role/BasicLambdaRole

functions:
  GetKey:
    handler: functions/GetKey/index.handler
    events:
      - httpApi:
          path: /api/keys
          method: GET
  GetMovies:
    handler: functions/GetMovies/index.handler
    events:
      - httpApi:
          path: /api/movies
          method: GET
  PostMovie:
    handler: functions/PostMovie/index.handler
    events:
      - httpApi:
          path: /api/movies
          method: POST
